"""Local Milvus standalone stack (etcd + MinIO + Milvus) for DiskANN experiments.

Milvus standalone is three containers, so unlike ``qdrant_runtime`` this module
renders a Compose project instead of issuing ``docker run``.

DiskANN is gated behind ``queryNode.enableDisk``, which is ``false`` by default.
It is enabled here through the ``QUERYNODE_ENABLEDISK`` environment variable —
Milvus maps an environment name onto a config key by lowercasing it and dropping
separators, the same mechanism the upstream Compose file uses for
``ETCD_ENDPOINTS`` and ``MINIO_ADDRESS``. That avoids replacing the image's full
``milvus.yaml``, where every key omitted from a hand-written file would silently
fall back to a compiled-in default.
"""

from __future__ import annotations

import time
import urllib.error
import urllib.request
from pathlib import Path
from urllib.parse import urlparse

from .docker_runtime import docker, ensure_compatible_storage, ensure_docker

DEFAULT_MILVUS_URI = "http://localhost:19530"
DEFAULT_MILVUS_PROJECT = "wikipedia-milvus"
DEFAULT_MILVUS_IMAGE = "milvusdb/milvus:v2.5.27"
DEFAULT_ETCD_IMAGE = "quay.io/coreos/etcd:v3.5.18"
DEFAULT_MINIO_IMAGE = "minio/minio:RELEASE.2024-05-28T17-19-04Z"
DEFAULT_HEALTH_PORT = 9091
DEFAULT_STARTUP_TIMEOUT = 300.0

COMPOSE_FILENAME = "docker-compose.yml"


def compose_file(
    *,
    project: str = DEFAULT_MILVUS_PROJECT,
    milvus_image: str = DEFAULT_MILVUS_IMAGE,
    etcd_image: str = DEFAULT_ETCD_IMAGE,
    minio_image: str = DEFAULT_MINIO_IMAGE,
    health_port: int = DEFAULT_HEALTH_PORT,
) -> str:
    """Render the Compose project.

    Volume paths are relative to the file, so the file must be written into the
    storage directory it describes.
    """
    return f"""\
# Generated by wikipedia.milvus_runtime — edits are overwritten.
services:
  etcd:
    container_name: {project}-etcd
    image: {etcd_image}
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ./volumes/etcd:/etcd
    command: >
      etcd -advertise-client-urls=http://etcd:2379
      -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio:
    container_name: {project}-minio
    image: {minio_image}
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ./volumes/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: {project}
    image: {milvus_image}
    command: ["milvus", "run", "standalone"]
    security_opt:
      - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      QUERYNODE_ENABLEDISK: "true"
    volumes:
      - ./volumes/milvus:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:{health_port}/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "19530:19530"
      - "{health_port}:{health_port}"
    depends_on:
      - "etcd"
      - "minio"
"""


def health_url(uri: str, health_port: int = DEFAULT_HEALTH_PORT) -> str:
    parsed = urlparse(uri)
    host = parsed.hostname or "localhost"
    return f"http://{host}:{health_port}/healthz"


def healthz_ok(url: str, timeout: float = 2.0) -> bool:
    try:
        with urllib.request.urlopen(url, timeout=timeout) as response:  # noqa: S310
            return response.status == 200
    except (urllib.error.URLError, OSError, ValueError):
        return False


def _write_if_changed(path: Path, content: str) -> bool:
    if path.is_file() and path.read_text(encoding="utf-8") == content:
        return False
    path.write_text(content, encoding="utf-8")
    return True


def _compose(storage: Path, project: str, *args: str):
    return docker(
        "compose",
        "-f",
        str(storage / COMPOSE_FILENAME),
        "-p",
        project,
        *args,
    )


def mounted_storage(container: str, destination: str = "/var/lib/milvus") -> Path | None:
    """Where a running container actually keeps its data, or None if absent."""
    result = docker(
        "container",
        "inspect",
        "--format",
        '{{range .Mounts}}{{if eq .Destination "'
        + destination
        + '"}}{{.Source}}{{end}}{{end}}',
        container,
    )
    if result.returncode != 0:
        return None
    source = result.stdout.strip()
    return Path(source).resolve() if source else None


def ensure_milvus(
    uri: str,
    *,
    storage_dir: str | Path | None = None,
    project: str = DEFAULT_MILVUS_PROJECT,
    image: str = DEFAULT_MILVUS_IMAGE,
    health_port: int = DEFAULT_HEALTH_PORT,
    startup_timeout: float = DEFAULT_STARTUP_TIMEOUT,
) -> str:
    """Bring up the local stack and return ``"started"`` or ``"already running"``."""
    health = health_url(uri, health_port)
    local = urlparse(uri).hostname in {"localhost", "127.0.0.1", "::1"}
    if not local:
        if healthz_ok(health):
            return "already running"
        raise RuntimeError(f"Milvus is not reachable: {uri}")
    if storage_dir is None:
        raise RuntimeError(
            "Local Milvus storage is not configured; run "
            "`uv run wikipedia-ingest milvus --bundle-dir /absolute/path` first"
        )

    storage = Path(storage_dir).expanduser()
    if not storage.is_absolute():
        raise ValueError("Milvus storage directory must be an absolute path")
    storage = storage.resolve()
    ensure_compatible_storage(storage, engine="Milvus")
    for name in ("etcd", "minio", "milvus"):
        (storage / "volumes" / name).mkdir(parents=True, exist_ok=True)
    ensure_docker("Milvus")

    if docker("compose", "version").returncode != 0:
        raise RuntimeError(
            "`docker compose` is unavailable; Milvus standalone needs the Compose plugin"
        )

    rendered = _write_if_changed(
        storage / COMPOSE_FILENAME,
        compose_file(
            project=project, milvus_image=image, health_port=health_port
        ),
    )

    # A healthy stack on this port is not necessarily *this* stack: the Compose
    # project name is fixed, so an earlier run against a different bundle leaves
    # containers that answer healthz while serving another directory's data.
    expected = (storage / "volumes" / "milvus").resolve()
    actual = mounted_storage(project)
    if actual is not None and actual != expected:
        print(
            f"milvus: reconfiguring {project} storage {actual} -> {expected}",
            flush=True,
        )
        removed = _compose(storage, project, "down")
        if removed.returncode != 0:
            detail = removed.stderr.strip() or removed.stdout.strip()
            raise RuntimeError(f"Could not replace Milvus stack: {detail}")
    elif not rendered and actual is not None and healthz_ok(health):
        return "already running"

    print(f"milvus: starting {project} with storage {storage}", flush=True)
    started = _compose(storage, project, "up", "-d")
    if started.returncode != 0:
        detail = started.stderr.strip() or started.stdout.strip()
        raise RuntimeError(f"Could not start Milvus stack: {detail}")

    deadline = time.monotonic() + startup_timeout
    announced = 0.0
    while time.monotonic() < deadline:
        if healthz_ok(health):
            return "started"
        waited = startup_timeout - (deadline - time.monotonic())
        if waited - announced >= 30:
            announced = waited
            print(f"milvus: waiting for healthz ({waited:.0f} s)", flush=True)
        time.sleep(2)
    logs = _compose(storage, project, "logs", "--tail", "40", "standalone")
    raise RuntimeError(
        f"Milvus did not become healthy within {startup_timeout:.0f} seconds.\n"
        f"{logs.stdout.strip() or logs.stderr.strip()}"
    )
